### ISSUE TITLE
Error on OwnerRepository Bean

### ISSUE THREAD

**Issue by Himovic** [Himovic/sfg-clinic-pet#61]

**Comment by mslowiak** [comment]
I will look on it tomorrow. Reopen it if still valid issue :)

**Comment by Himovic** [comment]
Sure. Thank you :)

**Comment by mslowiak** [comment]
@Himovic 
Well I fixes it right now, you don't need to wait to morning.
You got two packages so you need to specify where are entities and repositories.

Created pull request :)
Feel free to merge it

**Comment by Himovic** [comment]
Oooh it worked =D . Thank you so much for your help.
